"""initial schema

Creates every table for the Prisoner's Dilemma backend.

Enum handling: several columns share the same enum type (both action columns
in tournament_rounds and in human_rounds all use `action`). On PostgreSQL a
CREATE TABLE would try to CREATE TYPE once per table and fail the second time,
so the types are created up front with checkfirst and the columns then
reference them without re-creating. On SQLite, where enums compile to VARCHAR
plus a CHECK constraint, the plain type is used.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-12
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ENUM_TYPES: dict[str, tuple[str, ...]] = {
    "action": ("COOPERATE", "DEFECT"),
    "user_role": ("ADMIN", "TEACHER", "STUDENT"),
    "strategy_category": ("NICE", "NASTY", "STOCHASTIC"),
    "tournament_status": ("PENDING", "RUNNING", "COMPLETED", "FAILED"),
    "experiment_status": ("DRAFT", "RUNNING", "COMPLETED"),
    "survey_question_type": ("EXPECTED_COOPERATION", "TRUST_AFTER"),
}


def _enum(name: str) -> sa.types.TypeEngine:
    """The column type for an enum, appropriate to the current dialect."""
    values = ENUM_TYPES[name]
    if op.get_bind().dialect.name == "postgresql":
        return postgresql.ENUM(*values, name=name, create_type=False)
    return sa.Enum(*values, name=name)


def _create_enum_types() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    for name, values in ENUM_TYPES.items():
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)


def _drop_enum_types() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    for name, values in ENUM_TYPES.items():
        postgresql.ENUM(*values, name=name).drop(bind, checkfirst=True)


def upgrade() -> None:
    _create_enum_types()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('category', _enum("strategy_category"), nullable=False),
    sa.Column('is_deterministic', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', _enum("user_role"), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('payoff_matrices',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('cc_player_a', sa.Float(), nullable=False),
    sa.Column('cc_player_b', sa.Float(), nullable=False),
    sa.Column('cd_player_a', sa.Float(), nullable=False),
    sa.Column('cd_player_b', sa.Float(), nullable=False),
    sa.Column('dc_player_a', sa.Float(), nullable=False),
    sa.Column('dc_player_b', sa.Float(), nullable=False),
    sa.Column('dd_player_a', sa.Float(), nullable=False),
    sa.Column('dd_player_b', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payoff_matrices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payoff_matrices_name'), ['name'], unique=True)

    op.create_table('experiments',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', _enum("experiment_status"), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('anonymous_mode', sa.Boolean(), nullable=False),
    sa.Column('trust_survey_enabled', sa.Boolean(), nullable=False),
    sa.Column('payoff_matrix_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payoff_matrix_id'], ['payoff_matrices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_payoff_matrix_id'), ['payoff_matrix_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_status'), ['status'], unique=False)

    op.create_table('tournaments',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', _enum("tournament_status"), nullable=False),
    sa.Column('strategy_codes', sa.JSON(), nullable=False),
    sa.Column('rounds_per_match', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('continuation_probability', sa.Float(), nullable=True),
    sa.Column('include_self_play', sa.Boolean(), nullable=False),
    sa.Column('payoff_matrix_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payoff_matrix_id'], ['payoff_matrices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_payoff_matrix_id'), ['payoff_matrix_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_status'), ['status'], unique=False)

    op.create_table('experiment_participants',
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'code', name='uq_participant_code_per_experiment')
    )
    with op.batch_alter_table('experiment_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_participants_experiment_id'), ['experiment_id'], unique=False)

    op.create_table('tournament_matches',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('repetition', sa.Integer(), nullable=False),
    sa.Column('strategy_a_code', sa.String(length=60), nullable=False),
    sa.Column('strategy_b_code', sa.String(length=60), nullable=False),
    sa.Column('rounds_played', sa.Integer(), nullable=False),
    sa.Column('player_a_score', sa.Float(), nullable=False),
    sa.Column('player_b_score', sa.Float(), nullable=False),
    sa.Column('player_a_cooperation_count', sa.Integer(), nullable=False),
    sa.Column('player_b_cooperation_count', sa.Integer(), nullable=False),
    sa.Column('winner_code', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_matches_strategy_a_code'), ['strategy_a_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_matches_strategy_b_code'), ['strategy_b_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_matches_tournament_id'), ['tournament_id'], unique=False)
        batch_op.create_index('ix_tournament_matches_tournament_sequence', ['tournament_id', 'sequence'], unique=False)

    op.create_table('tournament_results',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_code', sa.String(length=60), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('rounds_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('cooperation_count', sa.Integer(), nullable=False),
    sa.Column('defection_count', sa.Integer(), nullable=False),
    sa.Column('cooperation_rate', sa.Float(), nullable=False),
    sa.Column('defection_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_results_rank'), ['rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_results_tournament_id'), ['tournament_id'], unique=False)
        batch_op.create_index('ix_tournament_results_tournament_strategy', ['tournament_id', 'strategy_code'], unique=True)

    op.create_table('human_matches',
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('pair_number', sa.Integer(), nullable=False),
    sa.Column('participant_a_id', sa.Uuid(), nullable=False),
    sa.Column('participant_b_id', sa.Uuid(), nullable=False),
    sa.Column('player_a_score', sa.Float(), nullable=False),
    sa.Column('player_b_score', sa.Float(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_a_id'], ['experiment_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_b_id'], ['experiment_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_matches_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_matches_participant_a_id'), ['participant_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_matches_participant_b_id'), ['participant_b_id'], unique=False)

    op.create_table('tournament_rounds',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('player_a_action', _enum("action"), nullable=False),
    sa.Column('player_b_action', _enum("action"), nullable=False),
    sa.Column('player_a_payoff', sa.Float(), nullable=False),
    sa.Column('player_b_payoff', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['tournament_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_rounds_match_id'), ['match_id'], unique=False)
        batch_op.create_index('ix_tournament_rounds_match_round', ['match_id', 'round_number'], unique=True)

    op.create_table('trust_surveys',
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('question_type', _enum("survey_question_type"), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['experiment_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'participant_id', 'question_type', name='uq_survey_answer_per_participant')
    )
    with op.batch_alter_table('trust_surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_surveys_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_surveys_participant_id'), ['participant_id'], unique=False)

    op.create_table('human_rounds',
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('player_a_id', sa.Uuid(), nullable=False),
    sa.Column('player_b_id', sa.Uuid(), nullable=False),
    sa.Column('player_a_action', _enum("action"), nullable=False),
    sa.Column('player_b_action', _enum("action"), nullable=False),
    sa.Column('player_a_payoff', sa.Float(), nullable=False),
    sa.Column('player_b_payoff', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['human_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_a_id'], ['experiment_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_b_id'], ['experiment_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'round_number', name='uq_human_round_per_match')
    )
    with op.batch_alter_table('human_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_rounds_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index('ix_human_rounds_experiment_round', ['experiment_id', 'round_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_rounds_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_rounds_match_id'))
        batch_op.drop_index('ix_human_rounds_experiment_round')
        batch_op.drop_index(batch_op.f('ix_human_rounds_experiment_id'))

    op.drop_table('human_rounds')
    with op.batch_alter_table('trust_surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_surveys_participant_id'))
        batch_op.drop_index(batch_op.f('ix_trust_surveys_experiment_id'))

    op.drop_table('trust_surveys')
    with op.batch_alter_table('tournament_rounds', schema=None) as batch_op:
        batch_op.drop_index('ix_tournament_rounds_match_round')
        batch_op.drop_index(batch_op.f('ix_tournament_rounds_match_id'))

    op.drop_table('tournament_rounds')
    with op.batch_alter_table('human_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_matches_participant_b_id'))
        batch_op.drop_index(batch_op.f('ix_human_matches_participant_a_id'))
        batch_op.drop_index(batch_op.f('ix_human_matches_experiment_id'))

    op.drop_table('human_matches')
    with op.batch_alter_table('tournament_results', schema=None) as batch_op:
        batch_op.drop_index('ix_tournament_results_tournament_strategy')
        batch_op.drop_index(batch_op.f('ix_tournament_results_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_results_rank'))

    op.drop_table('tournament_results')
    with op.batch_alter_table('tournament_matches', schema=None) as batch_op:
        batch_op.drop_index('ix_tournament_matches_tournament_sequence')
        batch_op.drop_index(batch_op.f('ix_tournament_matches_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_tournament_matches_strategy_b_code'))
        batch_op.drop_index(batch_op.f('ix_tournament_matches_strategy_a_code'))

    op.drop_table('tournament_matches')
    with op.batch_alter_table('experiment_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_participants_experiment_id'))

    op.drop_table('experiment_participants')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_status'))
        batch_op.drop_index(batch_op.f('ix_tournaments_payoff_matrix_id'))
        batch_op.drop_index(batch_op.f('ix_tournaments_name'))

    op.drop_table('tournaments')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_status'))
        batch_op.drop_index(batch_op.f('ix_experiments_payoff_matrix_id'))
        batch_op.drop_index(batch_op.f('ix_experiments_name'))

    op.drop_table('experiments')
    with op.batch_alter_table('payoff_matrices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payoff_matrices_name'))

    op.drop_table('payoff_matrices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_code'))

    op.drop_table('strategies')
    # ### end Alembic commands ###
    _drop_enum_types()
