"""Generate SYNTHETIC demo data so the experiment pipeline can be tested.

This is NOT experimental data. It is invented by a random model and must never
appear in the report as a result. Replace data/human_experiment.csv with the
real class sheet before writing Chapter 5.

Model used: each player starts fairly cooperative, mostly reciprocates the
opponent's previous move, and defects more often in the final rounds.
"""

import os
import random

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "data", "synthetic_demo.csv")

PAIRS = 10
ROUNDS = 10


def main(seed=7):
    rng = random.Random(seed)
    rows = []

    for i in range(1, PAIRS + 1):
        pair = "P{:02d}".format(i)
        # Each pair gets its own cooperative disposition.
        disposition = [rng.uniform(0.35, 0.9), rng.uniform(0.35, 0.9)]
        trust_before = [rng.randint(2, 5), rng.randint(2, 5)]
        last = [None, None]
        cooperated = [0, 0]

        for rnd in range(1, ROUNDS + 1):
            endgame = 0.25 if rnd >= ROUNDS - 1 else 0.0
            choices = []
            for side in (0, 1):
                other_last = last[1 - side]
                p = disposition[side]
                if other_last == "D":
                    p *= 0.4          # reciprocate a defection
                elif other_last == "C":
                    p = min(1.0, p + 0.1)
                p = max(0.0, p - endgame)
                choice = "C" if rng.random() < p else "D"
                choices.append(choice)
                cooperated[side] += choice == "C"

            rows.append((pair, rnd, choices[0], choices[1], trust_before))
            last = choices

        # Trust after play tracks how cooperative the opponent actually was.
        trust_after = [
            max(1, min(5, round(1 + 4 * cooperated[1] / ROUNDS))),
            max(1, min(5, round(1 + 4 * cooperated[0] / ROUNDS))),
        ]
        for idx in range(len(rows) - ROUNDS, len(rows)):
            pair_, rnd_, a_, b_, tb = rows[idx]
            rows[idx] = (pair_, rnd_, a_, b_, tb, trust_after)

    with open(OUT, "w", encoding="utf-8", newline="") as fh:
        fh.write("# SYNTHETIC DEMO DATA - generated by scripts/make_synthetic_demo.py\n")
        fh.write("# Not real participants. Do not report these numbers as results.\n")
        fh.write("pair,round,choice_a,choice_b,trust_before_a,trust_before_b,"
                 "trust_after_a,trust_after_b\n")
        for pair, rnd, a, b, tb, ta in rows:
            fh.write("{},{},{},{},{},{},{},{}\n".format(
                pair, rnd, a, b, tb[0], tb[1], ta[0], ta[1]))

    print("wrote {} ({} rows)".format(OUT, len(rows)))


if __name__ == "__main__":
    main()
